### ISSUE TITLE
Every elemental attack should add a minor (scalable) debuff(?)

### ISSUE THREAD

**Issue by StygianEmperor** [Tavi007/ElementalCombat#28]
Schöne Grüße! (I don't actually speak Deutsche but I attempted to learn in it in high school.)

I'm a D&D homebrewer at heart with next-to-zero scripting knowledge so this will probably not be super helpful, and forgive me if the mod already does this, but I feel that there should be a second layer to choosing your elements and damage sources (styles) tactically, rather than only playing rock-paper-scissors with resistances. Elemental damage in most games comes with a temporary (if often minor) debuff unique to that element which makes it have some more "personality" than just reducing HP faster or slower. So I was thinking something along these lines:

### Elements: (parentheses denote some possible alternate names)
- **Fire (heat):** ignition dealing damage over time and/or fear effect.
- **Cold (ice, frost):** slows movespeed/attack rate (or just reduced damage if attack rate is fixed)
- **Lightning (electric, shock):** stun (briefly stops the target entirely) and/or chain lightning (damages a different nearby target)
- **Poison (toxic, biohazard):** poisons, dealing DoT and/or weakening the target's damage output
- **Acid (corrosive):** burns, dealing DoT and/or weakening the target's damage resistance (particularly physical resistance - probably shouldn't be able weaken resistance to acid itself)
- **Sonic (thunder/noise):** increased knockback and/or tinnitus (temp. deafness) effect if you can do that in minecraft
- **Necrotic (death):** basically Wither, but undead could have high enough base resistance to heal from it and/or the attacker could steal health with it
- **Radiant (solar, radiation):** Harms undead especially or causes them to flee, and can cause temporary blindness in the living.
- **Psychic ("raw" or catch-all non-specific magic):** Temporary confusion and/or fear effect. Should work on anything animate, including undead.
- **Physical (kinetic):** bleeding DoT at most; should have no particular weaknesses or strengths.

Water and wind should probably deal cold or physical (or occasionally fire/heat) damage with a bludgeoning "Style," or source, as below:

### Sources (styles):
_(1-4 are physical damage types on an inverse scale of physical armor penetration/base damage based on how medieval weapons were designed for armor types)_
1. **Bludgeoning (crushing, smashing, explosions):** Bludgeoning weapons such as maces and warhammers can crush armor with the focused weight of percussive action, but lacking any cutting edges, such weapons aren't well-specialized against flesh or soft armor. Explosions tend to "crush" things apart, as well. _May require mods that add specialized bludgeoning weapons._ **(highest penetration/lowest base damage)**
2. **Hacking (chopping):** While not as percussive as bludgeoning, hacking weapons such as axes and war picks are decent weapons for getting through armor, and though relatively ungainly due to their distant point-of-balance from the hand compared to swords, hacking weapons are still able to inflict deep open wounds in soft targets. **(high penetration/low base damage)**
3. **Piercing (puncture, impalement):** Arrows, bolts, bullets, spears (including tridents), and straight swords such as arming swords and rapiers tend to deal piercing damage, which on a good hit can find vital organs in a soft target, and on a *very* good hit can even penetrate weak spots in armor such as the joints. **(low penetration/high base damage)**
4. **Slashing (slicing):** Curved swords such as falchions, Großesmessers, katanas, scimitars, and sabers; and other non-percussive edged weapons such as chakrams, claws, sickles, and war-scythes are incredibly effective against lightly- and un-armored targets as they can open large wounds with very little effort, but are almost worthless against heavy armor such as mail, brigandine, and especially plate. (lowest penetration/highest base damage) _Would require mods that add specialized slashing weapons._ **(lowest penetration/highest base damage)**
5. **Energy (catch-all nonspecific damage source):** Anything that does not utilize kinetic impact to cause harm, such as liquid or gaseous hazards or the sun.
6. **Punching?:** I'd honestly either make punching deal extremely low bludgeoning damage or have its own generic damage type with no penetration.

I don't think elemental strengths should be tied to weaknesses, but instead each element should be resisted/vulnerable individually - so someone could have great fire/cold/lightning resist but poor psychic and necrotic resistance or whatever. Basically getting rid of the opposing elements thing, even if some seem a natural fit it will probably hamstring you in the end.

Hope that's helpful and I'm not just talking to hear my own voice here. I'd love to learn enough to make mods myself at some point.

**Comment by Tavi007** [comment]
Hey!
Thank you for taking interest in my mod :)

While I do like the suggestion generally, it does not fit in with the main idea I had for the mod. I only ever wanted this weakness/resistance chart, which in itself should hopefully be enough to give the player the incentive to switch their gear. 

Anything more like the bleeding or slowing effect from modded items should be in the hands of this mod developer. This dev then can use my provided API to give their items additional information, so their mod will work together with mine. This way this dev has full control over the balance of their items.
