### ISSUE TITLE
Ticking entity bug

### ISSUE THREAD

**Issue by Beelover05** [Tavi007/ElementalCombat#67]
[crash-2023-06-09_12.13.38-server.txt](https://github.com/Tavi007/ElementalCombat/files/11705718/crash-2023-06-09_12.13.38-server.txt)
Happens quite frequently (there has been no config changes) and appears to happen as the stray is within powdered snow.
Update - This has caused my world to be unable to load and I cannot rejoin.

**Comment by Tavi007** [comment]
thank you for the crash report. I will look at the issue in the next few days and hopefully find a quick fix

**Comment by Beelover05** [comment]
I managed to fix it by changing the difficulty of the world, there's no rush!

**Comment by Tavi007** [comment]
I just released a new version that should fix the encountered NullPointerException.
