### ISSUE TITLE
Another ticking entity bug

### ISSUE THREAD

**Issue by Beelover05** [Tavi007/ElementalCombat#69]
Immunity given by certain items can cause compatibility issues, In this case it was a poison immunity ring from iron's spells. When worn it causes a crash. 
[crash-2023-06-18_01.29.34-client.txt](https://github.com/Tavi007/ElementalCombat/files/11780882/crash-2023-06-18_01.29.34-client.txt)

**Comment by Tavi007** [comment]
I just released a new version that should fix the encountered NullPointerException. (it was the same as the other reported bug)

Thank you again for the feedback!
