### ISSUE TITLE
General support

### ISSUE THREAD

**Issue by BitBork** [Tavi007/ElementalCombat#71]
Hi there Tavi007,

**Huge** fan of the mod, it adds a whole new aspect to Minecraft's combat in an innovative way!

I'm currently in the (slow) process of creating a private modpack for me and some friends to play, but I unfortunately can not get the damage types/elemental types to apply on any mob for the life of me... I have looked at your github wiki, saw your YT video and tried your pre-made datapacks, to no success. I was able to apply/change damage types on items however (such as Epic Knight's weapons).

The only thing I'd think it could be, would be another mod interfering with Elemental Combat. I also noticed the WAILA/HWYLA plugin does not seem to work on Jade, having that sorted would help immensely because I'm having a hard time tracking whether my datapack made any changes to mobs or not.
I tried putting mine and your datapacks in several locations, such as the _Global Datapacks mod_ directory, in the instance data- and resourcepack folder and in the world's data- and resourcepack folder.

I'm on Minecraft 1.18.2 Forge using Modrinth.
My current filestructure (for eg the zombie) is:
`minecraft instance/global_packs/required_data/datapack name/data/modid/elemental_combat_properties/mobs/zombie.json`
For the jason itself I used the structure from your wiki:'
```
{
	"attack_style":"",
	"attack_element":"",
	
	"defense_style":{
		"slash":5,
		"stab":5,
		"hit":5
	},
	
	"defense_element":{
		"light":-100
	}
}
```
(it's currently set to -100 because I wanted to see it worked _at all_, which it didn't)

Could you please help me figure out what is causing issues or what I'm doing wrong?
Sorry if this is not the appropriate place to ask for general help, but I couldn't see where else to contact you. 
If you need any info, files or screens lmk!

**Comment by BitBork** [comment]
Thanks for the quick reply! I still cannot get it to work however...

Some changes do happen ingame, as the zombie that I'm trying to change does seem to still be weak to light, but I think that's applied because that change is included within the mod itself. Could it maybe be that the datapack doesn't override the base mod changes to mobs?

Tried `combat_properties`, even tested on a fresh instance without any game-altering mods. Any help?
Also how would I get the Jade plugin to work? That'd help a lot.

**Comment by BitBork** [comment]
I found the issue. Big facepalm.

I hadn't thought of checking the logs, that got me to find the issue: the datapack had an uppercase case M for the minecraft modid folder, making it not register... So it was a matter of syntax that I didn't see (syntax can really rile me up sometimes hahah). I'll keep an eye on the logs as I script more and make sure I got my syntax correct before asking for help in the future (still relatively new to it all).

Was able to confirm it works right away by switching to WTHIT so the plugin works. Very glad it seems to be sorted now. I can finally get on with scripting! Thanks so much for the quick replies and the support!

Ps. Anywhere I could possibly get support if needed in the future, like a discord server?
Pss. If you'd like I have some suggestions for the mod still.

**Comment by Tavi007** [comment]
Good to hear that you found the fix :)

I don't have a discord for this mod, since I don't know how properly moderate it. I also wouldn't have the time to moderate it, since I also have a full time job.

I'm open to listen to suggestions, but I can not promise, that it will be implemented. I only have so much free time to work on minecraft mods.

**Comment by BitBork** [comment]
That's fair yeah, no worries.

I think I gave a suggestion in the comments a while ago:
"- I had the idea of adding damage types/resistances to curios to give a player a certain damage type or resistance when wearing said curio, any idea if this could work?"

Thanks again & keep at it!

**Comment by Tavi007** [comment]
Not sure what the features of the current released version are, but at least in my current wip version i already implemented the curios interaction. It iteracts the same way as normal equippment.

So either test it or wait for the next release :D

Gonna close the issue, since there aren't any question left :)
